version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.dagger:hilt-android-gradle-plugin
    versions:
    - 2.32-alpha
    - 2.33-beta
    - 2.34-beta
    - 2.34.1-beta
    - "2.35"
  - dependency-name: com.apollographql.apollo
    versions:
    - 2.5.5
    - 2.5.6
  - dependency-name: com.google.android.gms:oss-licenses-plugin
    versions:
    - 0.10.3
    - 0.10.4
  - dependency-name: androidx.navigation:navigation-safe-args-gradle-plugin
    versions:
    - 2.3.3
    - 2.3.4
    - 2.3.5
  - dependency-name: com.google.protobuf:protoc
    versions:
    - 3.15.6
    - 3.15.7
  - dependency-name: org.jetbrains.kotlin.plugin.serialization
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin.android
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: com.android.tools:desugar_jdk_libs
    versions:
    - 1.1.5
  - dependency-name: org.gradle.android.cache-fix
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 2.1.1
  - dependency-name: com.google.protobuf
    versions:
    - 0.8.15
