[versions]
androidx-lifecycle = "2.3.1"
androidx-navigation = "2.3.5"
androidx-paging = "3.0.0"
androidx-room = "2.3.0"
androidx-test = "1.3.0"
apollo = "2.5.8"
glide = "4.12.0"
google-hilt = "2.37"
google-protobuf = "3.17.3"
kotlinx-coroutine = "1.5.0"
okhttp = "4.9.1"

[libraries]
androidx-activity = "androidx.activity:activity-ktx:1.2.3"
androidx-annotation = "androidx.annotation:annotation:1.2.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.0"
androidx-constraint = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-core = "androidx.core:core-ktx:1.5.0"
androidx-datastore = "androidx.datastore:datastore:1.0.0-beta01"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.4"
androidx-leanback = "androidx.leanback:leanback:1.0.0"
androidx-lifecycleCompiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycleLiveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycleService = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewModelSavedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-navigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-pagingCommon = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
androidx-pagingRuntime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-recyclerView = "androidx.recyclerview:recyclerview:1.2.1"
androidx-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-roomKtx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-roomRuntime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-swipeRefresh = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-testCore = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-testJunit = "androidx.test.ext:junit-ktx:1.1.2"
androidx-testRules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-testRunner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-testTruth = { module = "androidx.test.ext:truth", version.ref = "androidx-test" }
androidx-viewPager2 = "androidx.viewpager2:viewpager2:1.0.0"
apollo-androidSupport = { module = "com.apollographql.apollo:apollo-android-support", version.ref = "apollo" }
apollo-api = { module = "com.apollographql.apollo:apollo-api", version.ref = "apollo" }
apollo-cacheSqlite = { module = "com.apollographql.apollo:apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-coroutine = { module = "com.apollographql.apollo:apollo-coroutines-support", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-okhttp3Integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
google-androidOssLicenses = "com.google.android.gms:play-services-oss-licenses:17.0.0"
google-hilt = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt" }
google-hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "google-hilt" }
google-material = "com.google.android.material:material:1.3.0"
google-protoc = { module = "com.google.protobuf:protoc", version.ref = "google-protobuf" }
google-protobufLite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "google-protobuf" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutine" }
kotlinx-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutine" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutine" }
kotlinx-serializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.1"
kotlinResult = "com.michael-bull.kotlin-result:kotlin-result:1.1.12"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:3.2.0"
okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
#okhttp-mockWebServerRule = { module = "com.squareup.okhttp3:mockwebserver3-junit4", version.ref = "okhttp" }
robolectric = "org.robolectric:robolectric:4.5.1"
tinyport-logger = "jp.tinyport:logger:0.1.0"

[bundles]
